- name: Deploy Traefik through Portainer for {{ item }}
  ansible.builtin.include_role:
    name: deploy-through-portainer
  vars:
    portainer_endpoint_name: "{{ item }}"
    portainer_stack_name: "{{ service_name }}-{{ item }}"
    portainer_stack_env: '[{\"name\": \"CF_DNS_API_TOKEN\", \"value\": \"{{ cloudflare_dns_api_token }}\"}]'
    service_compose_file: "{{ docker_compose_output }}"
    service_compose_file_changed: "{{ traefik_compose_file.changed }}"

- name: Add DNS rewrite for {{ item }}
  ansible.builtin.include_role:
    name: add-dns-rewrite
  vars:
    rewrite_domain: "{{ subdomain_prefix }}-{{ item }}.{{ cluster_domain }}"
    rewrite_answer: "{{ hostvars[item].ansible_host }}"

- name: Add Traefik to Homer Dashboard for {{ item }}
  ansible.builtin.include_role:
    name: add-to-homer
  vars:
    homer_service_name: "Services"
    homer_item:
      name: "Routing {{ item }}"
      subtitle: "Traefik"
      url: "https://{{ subdomain_prefix }}-{{ item }}.{{ cluster_domain }}"
      target: "_blank"
      logo: "logo-traefik.svg"