- name: Set portainer_stack_name
  ansible.builtin.set_fact:
    portainer_stack_name: "{{ service_name }}-{{ item }}"

- name: Check if stack exists in Portainer for {{ item }}
  ansible.builtin.uri:
    url: "{{ portainer_api_url }}/stacks?filters={\"EndpointId\":{{ existing_endpoints_map[item] }}}"
    method: GET
    headers:
      Authorization: "Bearer {{ portainer_api_token }}"
      Content-Type: "application/json"
    status_code: 200
  register: portainer_stacks_response

- name: Get stack matching name
  ansible.builtin.set_fact:
    stack_candidates: "{{ portainer_stacks_response.json | selectattr('Name', 'equalto', portainer_stack_name) | list }}"

- name: Find stack by name
  ansible.builtin.set_fact:
    portainer_stack_found: "{{ stack_candidates[0] }}"
  when: stack_candidates | length > 0

- name: Set fact if stack exists
  ansible.builtin.set_fact:
    stack_exists: "{{ portainer_stack_found is defined }}"

- name: Deploy or update Traefik stack for {{ item }}
  ansible.builtin.shell: |
    # Using curl instead of ansible.builtin.uri to ensure correct file uploads
    curl -X POST "{{ portainer_api_url_remote }}/stacks/create/standalone/file?endpointId={{ existing_endpoints_map[item] }}" \
      -H "Authorization: Bearer {{ portainer_api_token }}" \
      -F "Name=traefik-{{ item }}" \
      -F "Env=[{\"name\": \"CF_DNS_API_TOKEN\", \"value\": \"{{ cloudflare_dns_api_token }}\"}]" \
      -F "file=@{{ docker_compose_output }}"
  delegate_to: localhost
  when: traefik_compose_file.changed or not stack_exists

- name: Add DNS rewrite for {{ item }}
  ansible.builtin.include_role:
    name: add-dns-rewrite
  vars:
    rewrite_domain: "{{ traefik_subdomain_prefix }}-{{ item }}.{{ cluster_domain }}"
    rewrite_answer: "{{ hostvars[item].ansible_host }}"