- name: Deploy Traefik through Portainer for {{ item }}
  ansible.builtin.include_role:
    name: deploy-through-portainer
  vars:
    portainer_endpoint_name: "{{ item }}"
    portainer_stack_name: "{{ service_name }}-{{ item }}"
    service_compose_file: "{{ docker_compose_output }}"
    service_compose_file_changed: "{{ traefik_compose_file.changed }}"

- name: Add DNS rewrite for {{ item }}
  ansible.builtin.include_role:
    name: add-dns-rewrite
  vars:
    rewrite_domain: "{{ traefik_subdomain_prefix }}-{{ item }}.{{ cluster_domain }}"
    rewrite_answer: "{{ hostvars[item].ansible_host }}"