- name: Set dynamic output path
  ansible.builtin.set_fact:
    traefik_dynamic_output_file: "{{ traefik_dynamic_output }}/traefik-dynamic-{{ item }}.yml"

- name: Render Traefik dynamic template for {{ item }}
  ansible.builtin.template:
    src: "{{ traefik_dynamic_template }}"
    dest: "{{ traefik_dynamic_output_file }}"
    mode: "0644"
  delegate_to: localhost
  register: traefik_dynamic_rendered_template
  vars:
    destination_host: "{{ item }}"  # for the template context
  when: traefik_admin_password_changed or not (traefik_dynamic_output_file is file)

- name: Upload Traefik dynamic to host for {{ item }}
  ansible.builtin.copy:
    src: "{{ traefik_dynamic_output_file }}"
    dest: "{{ traefik_dynamic_file }}"
    mode: "0644"
  delegate_to: "{{ item }}"
  when: traefik_dynamic_rendered_template.changed