groups:
  - name: container.rules
    rules:
      - alert: ContainerNotRunning
        expr: |
          container_status == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Container not running"
          description: "Container '{{ $labels.name }}' on host '{{ $labels.host }}' not running ('{{ $labels.state }}')"