environment_name: prod

portainer_destination_host: "{{ groups['portainer_host'][0] }}"

apprise_destination_host: "{{ groups['apprise_host'][0] }}"

notifications_endpoint: "http://{{ hostvars[apprise_destination_host].ansible_host }}:{{ apprise_frontend_port }}/notify/apprise"

vaultwarden_destination_host: "{{ groups['vaultwarden_host'][0] }}"

mail_destination_host: "{{ groups['mail_host'][0] }}"
mail_destination_ip: "{{ hostvars[mail_destination_host].ansible_host }}"
mail_smtp_port: "{{ mailpit_smtp_port }}"
mail_smtp_admin_user: "{{ mailpit_smtp_admin_user }}"
mail_smtp_admin_password: "{{ mailpit_smtp_admin_password }}"