---
- name: Deploy portainer
  hosts: management
  become: no
  vars:
    portainer_data_path: "/storage/portainer/data"
    certs_base_path: "{{ cluster_output_path }}/certificates"
  vars_files:
    - vars/common.yaml
    - "{{ inventory_dir }}/docker-images.yaml"
    - "{{ inventory_dir }}/secrets.yaml"
    - "{{ inventory_dir }}/docker-ports.yaml"

  tasks:
    - name: Get portainer token and endpoints map
      ansible.builtin.include_role:
        name: get-portainer-token-and-endpoints-map

    - name: Set Portainer API URL
      set_fact:
        portainer_api_url_remote: "http://{{ hostvars['management'].ansible_host }}:{{ portainer_frontend_port }}/api"

    - name: Create missing endpoints
      ansible.builtin.shell: |
        # Using curl instead of ansible.builtin.uri to ensure correct file uploads
        curl -X POST "{{ portainer_api_url_remote }}/endpoints" \
          -H "Authorization: Bearer {{ portainer_api_token }}" \
          -F "Name={{ item }}" \
          -F "EndpointCreationType=1" \
          -F "ContainerEngine=docker" \
          -F "URL=tcp://{{ hostvars[item].ansible_host }}:2376" \
          -F "TLS=true" \
          -F "TLSSkipVerify=false" \
          -F "TLSSkipClientVerify=false" \
          -F "TLSCACertFile=@{{ certs_base_path }}/{{ cluster_name }}_root_ca_crt.pem;type=application/x-x509-ca-cert" \
          -F "TLSCertFile=@{{ certs_base_path }}/signed/docker-daemon-{{ item }}/docker-daemon-{{ item }}_crt.pem;type=application/pkix-cert" \
          -F "TLSKeyFile=@{{ certs_base_path }}/signed/docker-daemon-{{ item }}/docker-daemon-{{ item }}_key.pem;type=application/x-pem-file"
      delegate_to: localhost
      with_items: "{{ groups['docker_hosts'] }}"
      when: item not in portainer_endpoints_map
      # We use curl because ansible.builtin.uri does not preserve line endings in multipart file uploads

    - name: Copy TLS CA certificates for existing endpoints
      ansible.builtin.copy:
        src: "{{ certs_base_path }}/{{ cluster_name }}_root_ca_crt.pem"
        dest: "{{ portainer_data_path }}/tls/{{ portainer_endpoints_map[item] }}/ca.pem"
        owner: root
        group: root
        mode: '0600'
      with_items: "{{ portainer_endpoints_map.keys() }}"

    - name: Copy TLS crt for existing endpoints
      ansible.builtin.copy:
        src: "{{ certs_base_path }}/signed/docker-daemon-{{ item }}/docker-daemon-{{ item }}_crt.pem"
        dest: "{{ portainer_data_path }}/tls/{{ portainer_endpoints_map[item] }}/cert.pem"
        owner: root
        group: root
        mode: '0600'
      with_items: "{{ portainer_endpoints_map.keys() }}"

    - name: Copy TLS key for existing endpoints
      ansible.builtin.copy:
        src: "{{ certs_base_path }}/signed/docker-daemon-{{ item }}/docker-daemon-{{ item }}_key.pem"
        dest: "{{ portainer_data_path }}/tls/{{ portainer_endpoints_map[item] }}/key.pem"
        owner: root
        group: root
        mode: '0600'
      with_items: "{{ portainer_endpoints_map.keys() }}"
