---
- name: Deploy AdGuardHome to Portainer
  hosts: management
  gather_facts: false
  become: no
  vars:
    service_name: "adguardhome"
    destination_host: "dns"
    frontend_port: "3000"
    portainer_api_url: "http://localhost:9000/api"
    portainer_api_url_remote: "http://{{ hostvars[inventory_hostname].ansible_host }}:9000/api"
    portainer_destination_endpoint: "{{ destination_host }}"
    portainer_stack_name: "{{ service_name }}"
    docker_compose_template: "adguardhome/adguardhome-compose.yaml.j2"
    docker_compose_output: "{{ output_path }}/{{ cluster_name }}/docker-compose/adguardhome-compose.yaml"
    adguardhome_subdomain: "dns"
    adguardhome_config_template: "adguardhome/adguardhome-config.yaml.j2"
    adguardhome_config_output: "{{ output_path }}/{{ cluster_name }}/configs/adguardhome/adguardhome-config.yaml"
    adguardhome_password_checksum_file: "{{ output_path }}/{{ cluster_name }}/configs/adguardhome/adguardhome-admin-password-hash.txt"
    adguardhome_password_bcrypt_file: "{{ output_path }}/{{ cluster_name }}/configs/adguardhome/adguardhome-admin-password.txt"
    adguardhome_storage_base_dir: "/storage/adguardhome"
    adguardhome_config_dir: "{{ adguardhome_storage_base_dir }}/conf"
    adguardhome_volumes:
      - "{{ adguardhome_storage_base_dir }}/work:/opt/adguardhome/work"
      - "{{ adguardhome_config_dir }}:/opt/adguardhome/conf"
  vars_files:
    - vars/common.yaml
    - "{{ inventory_dir }}/docker-images.yaml"
    - "{{ inventory_dir }}/secrets.yaml"

  tasks:
    - name: Wait for Portainer API to be ready
      ansible.builtin.uri:
        url: "http://localhost:9000/api/status"
        method: GET
        return_content: yes
        status_code: 200
      register: portainer_status
      until: portainer_status.status == 200
      retries: 10
      delay: 5

    - name: Obtain Portainer API token
      ansible.builtin.uri:
        url: "{{ portainer_api_url }}/auth"
        method: POST
        body_format: json
        body:
          username: "{{ portainer_admin_user }}"
          password: "{{ portainer_admin_password }}"
        headers:
          Content-Type: "application/json"
        status_code: 200
      register: portainer_auth

    - name: Set API token as a fact
      ansible.builtin.set_fact:
        portainer_api_token: "{{ portainer_auth.json.jwt }}"

    - name: Get existing Portainer endpoints
      ansible.builtin.uri:
        url: "{{ portainer_api_url }}/endpoints"
        method: GET
        headers:
          Authorization: "Bearer {{ portainer_api_token }}"
        return_content: true
      register: existing_endpoints

    - name: Parse existing endpoints
      ansible.builtin.set_fact:
        existing_endpoints_map: "{{ existing_endpoints.json | items2dict(key_name='Name', value_name='Id') }}"

    - name: Existing endpoints
      ansible.builtin.debug:
        var: existing_endpoints_map

    - name: Set endpoint ID from name
      ansible.builtin.set_fact:
        endpoint_id: "{{ existing_endpoints_map[portainer_destination_endpoint] }}"

    - name: Endpoint selected
      ansible.builtin.debug:
        var: endpoint_id

    - name: Ensure required directories exist on the destination host
      ansible.builtin.file:
        path: "{{ item.split(':')[0] }}"
        state: directory
        mode: "0700"
      loop: "{{ adguardhome_volumes }}"
      delegate_to: "{{ destination_host }}"

    - name: Ensure the base directory for docker-compose output exists
      ansible.builtin.file:
        path: "{{ docker_compose_output | dirname }}"
        state: directory
        mode: "0755"
      delegate_to: "localhost"

    - name: Generate adguardhome-compose.yaml from template
      ansible.builtin.template:
        src: "{{ docker_compose_template }}"
        dest: "{{ docker_compose_output }}"
        mode: "0644"
      delegate_to: "localhost"
      register: adguardhome_compose_file

    - name: Ensure the base directory for AdGuardHome output config exists
      ansible.builtin.file:
        path: "{{ adguardhome_config_output | dirname }}"
        state: directory
        mode: "0755"
      delegate_to: "localhost"

    - name: Generate bcrypt password for AdGuard Home admin password
      ansible.builtin.include_role:
        name: generate-bcrypt-password
      vars:
        password_plaintext: "{{ adguardhome_admin_password }}"
        password_checksum_file: "{{ adguardhome_password_checksum_file }}"
        password_bcrypt_file: "{{ adguardhome_password_bcrypt_file }}"

    - name: Store the generated bcrypt password into a specific variable
      ansible.builtin.set_fact:
        adguardhome_admin_password_bcrypt: "{{ password_bcrypt }}"
        adguardhome_admin_password_changed: "{{ password_changed }}"

    - name: Generate adguardhome-config.yaml from template
      ansible.builtin.template:
        src: "{{ adguardhome_config_template }}"
        dest: "{{ adguardhome_config_output }}"
        mode: "0644"
      delegate_to: "localhost"
      register: adguardhome_config_file
      vars:
        rewrite_answer: "{{ hostvars[destination_host].ansible_host }}"
      when: adguardhome_admin_password_changed or not (adguardhome_config_output is file)

    - name: Upload new AdGuardHome config
      ansible.builtin.copy:
        src: "{{ adguardhome_config_output }}"
        dest: "{{ adguardhome_config_dir }}/AdGuardHome.yaml"
        mode: "0644"
      delegate_to: "{{ destination_host }}"
      when: adguardhome_config_file.changed

    - name: Check if stack exists in Portainer
      ansible.builtin.uri:
        url: "{{ portainer_api_url }}/stacks?filters={\"EndpointId\":{{ endpoint_id }}}"
        method: GET
        headers:
          Authorization: "Bearer {{ portainer_api_token }}"
          Content-Type: "application/json"
        status_code: 200
      register: portainer_stacks_response

    - name: Get stack matching name
      set_fact:
        stack_candidates: "{{ portainer_stacks_response.json | selectattr('Name', 'equalto', portainer_stack_name) | list }}"

    - name: Find stack by name
      set_fact:
        portainer_stack_found: "{{ stack_candidates[0] }}"
      when: stack_candidates | length > 0

    - name: Set fact if stack exists
      ansible.builtin.set_fact:
        stack_exists: "{{ portainer_stack_found is defined }}"

    - name: Deploy stack to Portainer (Create or Update)
      ansible.builtin.shell: |
        # Using curl instead of ansible.builtin.uri to ensure correct file uploads
        curl -X POST "{{ portainer_api_url_remote }}/stacks/create/standalone/file?endpointId={{ endpoint_id }}" \
          -H "Authorization: Bearer {{ portainer_api_token }}" \
          -F "Name={{ portainer_stack_name }}" \
          -F "file=@{{ docker_compose_output }}" \
      delegate_to: localhost
      when: adguardhome_compose_file.changed or not stack_exists