---
- name: Deploy MailRise to Portainer
  hosts: management
  gather_facts: false
  become: no
  vars:
    service_name: "mailrise"
    destination_host: "management"
    container_name: "{{ service_name }}"
    docker_compose_template: "mailrise/mailrise-compose.yaml.j2"
    docker_compose_output: "{{ cluster_output_path }}/docker-compose/mailrise-compose.yaml"
    ports:
      - ext: "{{ mailrise_port }}"
        int: 8025
    storage_base_dir: "/storage/mailrise"
    proxmox_notification_target_name: "{{ service_name }}"
    mailrise_config_template: "mailrise/mailrise.conf.j2"
    mailrise_config_output: "{{ cluster_output_path }}/configs/mailrise/mailrise.conf"
    mailrise_container_user: "mailrise"
    mailrise_config_dir: "{{ storage_base_dir }}/config"
    mailrise_config_file: "{{ mailrise_config_dir }}/mailrise.conf"
    mailrise_certs_dir: "{{ storage_base_dir }}/certs"
    mailrise_crt_file: "{{ mailrise_certs_dir }}/mailrise_crt.pem"
    mailrise_key_file: "{{ mailrise_certs_dir }}/mailrise_key.pem"
    mailrise_telegram_url: "tgram://{{ telegram_notification_bot_token }}/{{ telegram_chat_id }}"
    volumes:
      - src: "{{ mailrise_config_file }}"
        dst: "/etc/mailrise.conf:ro"
        type: file
      - src: "{{ mailrise_crt_file }}"
        dst: "/home/{{ mailrise_container_user }}/mailrise_crt.pem:ro"
        type: file
      - src: "{{ mailrise_key_file }}"
        dst: "/home/{{ mailrise_container_user }}/mailrise_key.pem:ro"
        type: file
  vars_files:
    - vars/common.yaml
    - "{{ inventory_dir }}/docker-images.yaml"
    - "{{ inventory_dir }}/secrets.yaml"
    - "{{ inventory_dir }}/docker-ports.yaml"

  tasks:
    - name: Extract MailRise named ports
      ansible.builtin.include_role:
        name: extract-named-ports-to-dict

    - name: Get portainer token and endpoints map
      ansible.builtin.include_role:
        name: get-portainer-token-and-endpoints-map

    - name: Ensure MailRise directories exist
      ansible.builtin.include_role:
        name: ensure-directories-exist
      vars:
        target_hosts: "{{ destination_host }}"

    - name: Ensure the base directory for MailRise output config exists
      ansible.builtin.file:
        path: "{{ mailrise_config_output | dirname }}"
        state: directory
        mode: "0755"
      delegate_to: "localhost"

    - name: Generate mailrise.conf from template
      ansible.builtin.template:
        src: "{{ mailrise_config_template }}"
        dest: "{{ mailrise_config_output }}"
        mode: "0644"
      delegate_to: "localhost"
      register: mailrise_config_parsed_template

    - name: Upload new MailRise config
      ansible.builtin.copy:
        src: "{{ mailrise_config_output }}"
        dest: "{{ mailrise_config_file }}"
        mode: "0644"
      delegate_to: "{{ destination_host }}"
      when: mailrise_config_parsed_template.changed

    - name: Generate signed certificate for MailRise
      ansible.builtin.command:
        cmd: >
          python scripts/generate-signed-certificate.py
          --base-path {{ certificate_tools_path }}
          --ca-alias {{ cluster_name }}
          --ca-cn "{{ cluster_name }} root ca"
          --signed-alias "{{ service_name }}"
          --signed-cn "{{ service_name }}.{{ cluster_domain }}"
          --signed-san-ip {{ hostvars[destination_host].ansible_host }}
          --output-format ansible
      register: signed_cert_output
      changed_when: (signed_cert_output.stdout | from_json).changed
      delegate_to: localhost

    - name: Parse output of signed certificate generation
      ansible.builtin.set_fact:
        ca_crt_path: "{{ (signed_cert_output.stdout | from_json).details['ca-crt-path'] }}"
        signed_crt_path: "{{ (signed_cert_output.stdout | from_json).details['signed-crt-path'] }}"
        signed_key_path: "{{ (signed_cert_output.stdout | from_json).details['signed-key-path'] }}"
      changed_when: false

    - name: Ensure CA certificate is copied to Proxmox
      ansible.builtin.copy:
        src: "{{ ca_crt_path }}"
        dest: "/usr/local/share/ca-certificates/{{ cluster_name }}_root_ca.crt"
        mode: "644"
      delegate_to: pve
      notify: Update trusted CAs

    - name: Copy certificates to MailRise
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - { src: "{{ signed_crt_path }}", dest: "{{ mailrise_crt_file }}" }
        - { src: "{{ signed_key_path }}", dest: "{{ mailrise_key_file }}" }

    - name: Generate mailrise-compose.yaml from template
      ansible.builtin.template:
        src: "{{ docker_compose_template }}"
        dest: "{{ docker_compose_output }}"
        mode: "0644"
      delegate_to: "localhost"
      register: mailrise_compose_file

    - name: Deploy MailRise through Portainer
      ansible.builtin.include_role:
        name: deploy-through-portainer
      vars:
        portainer_endpoint_name: "{{ destination_host }}"
        portainer_stack_name: "{{ service_name }}"
        service_compose_file: "{{ docker_compose_output }}"
        service_compose_file_changed: "{{ mailrise_compose_file.changed }}"

    - name: Authenticate to Proxmox API
      uri:
        url: "https://localhost:8006/api2/json/access/ticket"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ proxmox_user }}@pam"
          password: "{{ proxmox_password }}"
        validate_certs: false
      delegate_to: pve
      register: proxmox_login_response

    - name: Check if SMTP target already exists
      uri:
        url: "https://localhost:8006/api2/json/cluster/notifications/targets"
        method: GET
        headers:
          Cookie: "PVEAuthCookie={{ proxmox_login_response.json.data.ticket }}"
          CSRFPreventionToken: "{{ proxmox_login_response.json.data.CSRFPreventionToken }}"
        validate_certs: false
      delegate_to: pve
      register: proxmox_existing_notification_targets

    - name: Determine if SMTP target exists
      ansible.builtin.set_fact:
        proxmox_notification_target_exists: "{{ proxmox_notification_target_name in proxmox_existing_notification_targets.json.data | map(attribute='name') | list }}"

    - name: Add notification target
      uri:
        url: "https://localhost:8006/api2/json/cluster/notifications/endpoints/smtp"
        method: POST
        headers:
          Cookie: "PVEAuthCookie={{ proxmox_login_response.json.data.ticket }}"
          CSRFPreventionToken: "{{ proxmox_login_response.json.data.CSRFPreventionToken }}"
        validate_certs: false
        body_format: json
        body:
          name: "mailrise"
          comment: "Send notifications to Telegram chatbot using MailRise"
          mailto: "telegram@mailrise.xyz"
          server: "{{ hostvars[destination_host].ansible_host }}"
          port: 8025
          from-address: "root@pve.local"
          username: "{{ mailrise_admin_user }}"
          password: "{{ mailrise_admin_password }}"
          mode: "starttls"
        status_code: 200
      delegate_to: pve
      when: not proxmox_notification_target_exists
      register: add_notification_target_result

  handlers:
    - name: Update trusted CAs
      ansible.builtin.command: update-ca-certificates
      delegate_to: pve
      register: update_trusted_cas_result
      changed_when: "'0 added, 0 removed' not in update_trusted_cas_result.stdout"
