# Role: get-portainer-token-and-endpoints-map
#
# This role manages DNS rewrite rules in AdGuard Home via its HTTP API.
# It checks if a rewrite rule exists for a given domain and adds it if missing.
#
# INPUT VARIABLES:
# ----------------
#
#
# OUTPUT FACTS:
# -------------
# portainer_api_token
# portainer_endpoints_map

- name: Wait for Portainer API to be ready
  ansible.builtin.uri:
    url: "{{ portainer_api_url }}/status"
    method: GET
    return_content: yes
    status_code: 200
  register: portainer_status
  until: portainer_status.status == 200
  retries: 10
  delay: 5
  delegate_to: management

- name: Obtain Portainer API token
  ansible.builtin.uri:
    url: "{{ portainer_api_url }}/auth"
    method: POST
    body_format: json
    body:
      username: "{{ portainer_admin_user }}"
      password: "{{ portainer_admin_password }}"
    headers:
      Content-Type: "application/json"
    status_code: 200
  register: portainer_auth
  delegate_to: management

- name: Set API token as a fact
  ansible.builtin.set_fact:
    portainer_api_token: "{{ portainer_auth.json.jwt }}"

- name: Get existing Portainer endpoints
  ansible.builtin.uri:
    url: "{{ portainer_api_url }}/endpoints"
    method: GET
    headers:
      Authorization: "Bearer {{ portainer_api_token }}"
    return_content: true
  register: portainer_existing_endpoints
  delegate_to: management

- name: Parse existing endpoints
  ansible.builtin.set_fact:
    portainer_endpoints_map: "{{ portainer_existing_endpoints.json | items2dict(key_name='Name', value_name='Id') }}"

- name: Existing endpoints
  ansible.builtin.debug:
    var: portainer_endpoints_map